export enum ControllerEventStreamNamesEnum {
  AUTH_EVENT_SOURCE = 'AUTH_EVENT_SOURCE',
  DATA_BASE_EVENT_STREAM = 'DATA_BASE_EVENT_STREAM',
  WEBSOCKET_EVENT_STREAM = 'WEBSOCKET_EVENT_STREAM',
  HTTP_EVENT_STREAM = 'HTTP_EVENT_STREAM',
}
